/**
 * dsh-skins build — 把 src/client.core.js 与 themes/、skins/ 资源内联成 lib/client.js。
 *
 * 用法：
 *   node build.mjs          生成 lib/client.js
 *   node build.mjs --check  校验现有产物是否最新（过时以非零码退出）
 *
 * 产物契约（手动渠道客户端 bundle，对齐 dsh-theme-gallery 的加载形态）：
 *   window.__ModuleLoader__.load({ id: "dsh-skins", factory: (require) => { ... } })
 */
import { readFile, writeFile, readdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const checkOnly = process.argv.includes('--check')

const ACCENT_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/
const BODY_ATTR_RE = /^data-dsh-skin-[a-z0-9-]+$/

function fail(message) {
  const error = new Error(`[dsh-skins build] ${message}`)
  error.isBuildError = true
  throw error
}

/** 读取并校验 themes/*.json。 */
async function loadThemes() {
  const dir = join(root, 'themes')
  const files = (await readdir(dir)).filter((name) => name.endsWith('.json')).sort()
  if (files.length === 0) fail('no theme families under themes/')
  const themes = []
  const seen = new Set()
  for (const file of files) {
    let data
    try {
      data = JSON.parse(await readFile(join(dir, file), 'utf8'))
    } catch (error) {
      fail(`themes/${file}: invalid JSON (${error.message})`)
    }
    if (typeof data.id !== 'string' || data.id.length === 0) fail(`themes/${file}: missing id`)
    if (seen.has(data.id)) fail(`themes/${file}: duplicate theme id "${data.id}"`)
    seen.add(data.id)
    if (typeof data.label !== 'string' || data.label.length === 0) fail(`themes/${file}: missing label`)
    if (!data.preview || !data.preview.light || !data.preview.dark) fail(`themes/${file}: preview must carry light and dark`)
    if (!data.tokens || typeof data.tokens !== 'object' || Array.isArray(data.tokens)) fail(`themes/${file}: tokens must be an object`)
    for (const [name, value] of Object.entries(data.tokens)) {
      if (typeof value !== 'object' || value === null || typeof value.light !== 'string' || typeof value.dark !== 'string') {
        fail(`themes/${file}: token "${name}" must be a { light, dark } string pair`)
      }
    }
    themes.push(data)
  }
  return themes
}

/** 读取并校验 skins/<id>/{skin.json,skin.css,a11y.css}。 */
async function loadSkins() {
  const dir = join(root, 'skins')
  const entries = await readdir(dir, { withFileTypes: true })
  const skinDirs = entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort()
  const skins = []
  const seen = new Set()
  for (const id of skinDirs) {
    const skinDir = join(dir, id)
    const manifestPath = join(skinDir, 'skin.json')
    const cssPath = join(skinDir, 'skin.css')
    const a11yPath = join(skinDir, 'a11y.css')
    if (!existsSync(manifestPath)) fail(`skins/${id}: missing skin.json`)
    if (!existsSync(cssPath)) fail(`skins/${id}: missing skin.css`)
    let manifest
    try {
      manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
    } catch (error) {
      fail(`skins/${id}/skin.json: invalid JSON (${error.message})`)
    }
    if (manifest.id !== id) fail(`skins/${id}/skin.json: id "${manifest.id}" must match its directory "${id}"`)
    if (seen.has(manifest.id)) fail(`skins/${id}: duplicate skin id "${manifest.id}"`)
    seen.add(manifest.id)
    if (typeof manifest.bodyAttr !== 'string' || !BODY_ATTR_RE.test(manifest.bodyAttr)) {
      fail(`skins/${id}/skin.json: bodyAttr must look like data-dsh-skin-<id>`)
    }
    if (typeof manifest.accent !== 'string' || !ACCENT_RE.test(manifest.accent)) {
      fail(`skins/${id}/skin.json: accent must be a hex color`)
    }
    const css = await readFile(cssPath, 'utf8')
    if (css.trim().length === 0) fail(`skins/${id}/skin.css is empty`)
    const a11y = existsSync(a11yPath) ? await readFile(a11yPath, 'utf8') : ''
    skins.push({ ...manifest, css, a11y })
  }
  return skins
}

/** 组装 lib/client.js 文本。 */
export async function build() {
  const themes = await loadThemes()
  const skins = await loadSkins()
  const core = await readFile(join(root, 'src', 'client.core.js'), 'utf8')
  if (!core.includes('/*@__THEMES__@*/') || !core.includes('/*@__SKINS__@*/')) {
    fail('src/client.core.js is missing the inlining markers')
  }
  const body = core
    .replace('/*@__THEMES__@*/', JSON.stringify(themes))
    .replace('/*@__SKINS__@*/', JSON.stringify(skins))
  // 语法自检：内联后必须仍是一段可解析的工厂函数体（不执行，仅编译）。
  try {
    // eslint-disable-next-line no-new-func
    new Function(body)
  } catch (error) {
    fail(`inlined factory body no longer parses (${error.message})`)
  }
  const output = [
    '// AUTO-GENERATED by build.mjs — do not edit by hand.',
    '// Re-run `node build.mjs` after changing src/, themes/, or skins/.',
    'window.__ModuleLoader__.load({',
    '\tid: "dsh-skins",',
    '\tfactory: (require) => {',
    '\t\tvar module = { exports: {} };',
    '\t\tvar exports = module.exports;',
    body,
    '\t\tmodule.exports = { apply };',
    '\t\treturn module.exports;',
    '\t}',
    '});',
    '',
  ].join('\n')
  return { output, themeCount: themes.length, skinCount: skins.length }
}

async function main() {
  try {
    const { output, themeCount, skinCount } = await build()
    const target = join(root, 'lib', 'client.js')
    if (checkOnly) {
      const existing = existsSync(target) ? await readFile(target, 'utf8') : null
      if (existing !== output) {
        console.error('[dsh-skins build] lib/client.js is out of date — run `node build.mjs`')
        process.exitCode = 1
      } else {
        console.log(`[dsh-skins build] lib/client.js is up to date (${themeCount} themes, ${skinCount} skins)`)
      }
      return
    }
    await writeFile(target, output)
    console.log(`[dsh-skins build] wrote lib/client.js (${themeCount} themes, ${skinCount} skins)`)
  } catch (error) {
    console.error(error && error.isBuildError ? error.message : error)
    process.exitCode = 1
  }
}

// 兼容 Node 20/22/24：以 argv 判断主入口（不依赖 import.meta.main）。
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await main()
}
